baseURL = "https://kaichu.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "KaiChu"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = "UA-65308340-1"                   # your google analytics id
disqusShortname = "kaichuio"                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "KaiChu"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "Life is unique by how you shape it"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "My spiritual home"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]                                  # site's keywords  # 网站关键字
  description = "KaiChu's blog"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  customCSS = ["add-on.css"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/cage1016"
  twitter = "https://twitter.com/CageChung"
  linkedin = "https://www.linkedin.com/in/kaichuchung"
  instagram = "https://www.instagram.com/cage1016/"
  slideshow = "https://www.slideshare.net/cagechung"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true